version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/building-microservices-with-go/chapter11-services-auth

    steps:
      - checkout
      - run: go get github.com/Masterminds/glide
      - run: glide up
      - run: make test
